from pydantic import BaseModel, Field
from datetime import datetime


class Product(BaseModel):
    """
    Represents a Product in the system.

    Attributes:
    - id: primary key (auto-generated by the database).
    - name: product name (required, 2-100 characters).
    - description: optional product description (up to 255 characters).
    - stock_id: ID of the stock containing this product.
    - quantity: available quantity in stock.
    - expiration_date: optional expiration date.
    - purchase_price: cost price in the stock.
    - sale_price: selling price.
    """

    id: int | None = Field(default=None, description="Primary key in the database")
    name: str = Field(..., min_length=2, max_length=100, description="Product name")
    description: str | None = Field(None, max_length=255, description="Optional product description")
    stock_id: float | None = Field(None, description="ID of the stock containing this product")
    quantity: float = Field(default=0, ge=0, description="Available quantity")
    expiration_date: datetime | None = Field(None, description="Expiration date (if applicable)")
    purchase_price: float = Field(default=0, ge=0, description="Purchase price")
    sale_price: float = Field(default=0, ge=0, description="Sale price")
